name: flutter_down_menu
description: Customize the drop-down menu, quickly realize the head drop-down menu,
  and support the rapid realization of single selection, multiple selection list, secondary list, single selection, multiple selection and other functions.

version: 0.0.5
homepage: https://github.com/lixp185/flutter_down_menu

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:


